/**
 * TSC wrapper, spawned by the CLI's `run_tsc_wrapper`.
 *
 * Wraps `tsc --noEmit` with macro expansion baked into file reads.
 * Files containing macros are expanded before being passed to the
 * TypeScript compiler.
 *
 * Arguments:
 *   argv[2]: tsconfig path (default: "tsconfig.json")
 *
 * Environment:
 *   MACROFORGE_TYPE_REGISTRY_PATH: path to pre-built type registry JSON
 *   MACROFORGE_DECLARATIVE_REGISTRY_PATH: path to pre-built declarative macro registry JSON
 */
import path from "node:path";
import {
  createExpandOptions,
  expandSourceResult,
  isMacroSourceFile,
  loadProjectModule,
  mapSpanToSource,
} from "./wrapper-common.mjs";

const ts = loadProjectModule("typescript");
const macros = loadProjectModule("@macroforge/core");

const formatHost = {
  getCanonicalFileName: (fileName) => fileName,
  getCurrentDirectory: ts.sys.getCurrentDirectory,
  getNewLine: () => ts.sys.newLine,
};

const projectArg = process.argv[2] || "tsconfig.json";
const configPath = ts.findConfigFile(
  process.cwd(),
  ts.sys.fileExists,
  projectArg,
);
if (!configPath) {
  console.error(`[macroforge] tsconfig not found: ${projectArg}`);
  process.exit(1);
}
const configFile = ts.readConfigFile(configPath, ts.sys.readFile);
if (configFile.error) {
  console.error(ts.formatDiagnostic(configFile.error, formatHost));
  process.exit(1);
}
const parsed = ts.parseJsonConfigFileContent(
  configFile.config,
  ts.sys,
  path.dirname(configPath),
);
const options = { ...parsed.options, noEmit: true };

const plugin = new macros.NativePlugin();
const expandOptions = createExpandOptions(macros);
const host = ts.createCompilerHost(options);
const originalGetSourceFile = host.getSourceFile.bind(host);

/**
 * Expanded files, by name: the source as written and the mapping from the
 * expansion back to it, so diagnostics are reported where the user wrote code.
 */
const expandedFiles = new Map();

host.getSourceFile = (fileName, languageVersion, ...rest) => {
  if (isMacroSourceFile(fileName)) {
    const sourceText = ts.sys.readFile(fileName);
    if (sourceText !== undefined) {
      const result = expandSourceResult(plugin, fileName, sourceText, expandOptions);
      if (result.sourceMapping) {
        expandedFiles.set(fileName, {
          original: ts.createSourceFile(fileName, sourceText, languageVersion, true),
          mapping: result.sourceMapping,
        });
      }
      return ts.createSourceFile(fileName, result.code, languageVersion, true);
    }
  }
  return originalGetSourceFile(fileName, languageVersion, ...rest);
};

/** Moves a diagnostic from a file's expansion onto its source. */
function toSource(diagnostic) {
  const expanded = diagnostic.file && expandedFiles.get(diagnostic.file.fileName);
  if (!expanded || diagnostic.start === undefined) return diagnostic;
  const span = mapSpanToSource(macros, expanded.mapping, diagnostic.start, diagnostic.length ?? 0);
  const moved = { ...diagnostic, file: expanded.original, start: span.start, length: span.length };
  if (span.generatedBy === undefined) return moved;
  return {
    ...moved,
    messageText: `in code generated by ${span.generatedBy}: ${ts.flattenDiagnosticMessageText(
      diagnostic.messageText,
      "\n",
    )}`,
  };
}

const program = ts.createProgram(parsed.fileNames, options, host);
const diagnostics = ts.getPreEmitDiagnostics(program).map(toSource);
for (const diagnostic of diagnostics) {
  console.error(ts.formatDiagnostic(diagnostic, formatHost).trimEnd());
}
const hasError = diagnostics.some(
  (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error,
);
process.exit(hasError ? 1 : 0);
