//! Rewrites one config module for the expanded config: each handler is
//! hoisted into a named export and each relative import re-rooted, so the
//! copy reads exactly what the original did.

use std::collections::HashSet;
use std::path::{Component, Path, PathBuf};

use macroforge_ts_syn::config::HandlerSite;
use oxc::allocator::Allocator;
use oxc::ast::ast::{
    Declaration, Expression, ImportExpression, ImportMeta, Program, Statement, StringLiteral,
};
use oxc::ast_visit::{Visit, walk};
use oxc::parser::Parser;
use oxc::span::{GetSpan, SourceType, Span};

use super::super::error::{MacroError, Result};

/// `module` copied with its handlers hoisted into exports and its relative
/// imports re-rooted for a file in `out_parent`.
pub(super) fn hoist_module(
    source: &str,
    module: &Path,
    sites: &[(&HandlerSite, String)],
    out_parent: &Path,
    root_dir: &Path,
) -> Result<String> {
    let fail =
        |message: String| MacroError::InvalidConfig(format!("{}: {message}", module.display()));
    let allocator = Allocator::default();
    let source_type = SourceType::from_path(module).unwrap_or_else(|_| SourceType::ts());
    let parsed = Parser::new(&allocator, source, source_type).parse();
    if let Some(diagnostic) = parsed.diagnostics.first() {
        return Err(fail(format!("could not parse: {diagnostic}")));
    }
    let program = &parsed.program;
    reject_relocation_hazards(program).map_err(fail)?;

    let module_dir = module.parent().unwrap_or(Path::new("."));
    let mut edits = Edits::default();
    for statement in &program.body {
        match statement {
            Statement::ImportDeclaration(import) => {
                reroot(&mut edits, &import.source, module_dir, out_parent);
            }
            Statement::ExportAllDeclaration(export) => {
                reroot(&mut edits, &export.source, module_dir, out_parent);
            }
            Statement::ExportFromDeclaration(export) => {
                reroot(&mut edits, &export.source, module_dir, out_parent);
            }
            Statement::ExportDeclaration(export) => {
                if let Declaration::VariableDeclaration(declaration) = &export.declaration {
                    mark_pure_initializers(&mut edits, declaration);
                }
            }
            Statement::VariableDeclaration(declaration) => {
                mark_pure_initializers(&mut edits, declaration);
            }
            Statement::ExportDefaultDeclaration(export) => {
                if let Some(expression) = export.declaration.as_expression() {
                    mark_pure(&mut edits, expression);
                }
            }
            Statement::ExpressionStatement(expression) => {
                return Err(fail(format!(
                    "`{}` runs when the config is imported; the expanded config is imported by \
                     generated code, so its top level may only declare",
                    slice(source, expression.span)
                )));
            }
            _ => {}
        }
    }

    let declared = top_level_names(program);
    let mut trailer = String::new();
    for (site, name) in sites {
        let span = Span::new(site.start, site.end);
        let statement = program
            .body
            .iter()
            .find(|statement| {
                statement.span().start <= span.start && span.end <= statement.span().end
            })
            .ok_or_else(|| fail(format!("no top-level statement holds the handler `{name}`")))?;
        if nested_in_function(statement, span) {
            return Err(fail(format!(
                "the handler `{name}` is declared inside a function; declare foreign types at the \
                 module's top level so their handlers can be exported"
            )));
        }
        match &site.identifier {
            Some(identifier) if declared.contains(identifier.as_str()) => {
                trailer.push_str(&format!("export {{ {identifier} as {name} }};\n"));
            }
            _ => {
                edits.insert(
                    statement.span().start,
                    format!("export const {name} = {};\n", top_level_text(source, span)),
                );
                edits.replace(span, name.clone());
            }
        }
    }

    let relative = module.strip_prefix(root_dir).unwrap_or(module);
    let mut output = format!(
        "// Generated by macroforge from {}. Edit that file, not this one.\n",
        slash_path(relative)
    );
    let edited = edits.apply(source).map_err(|(start, end)| {
        fail(format!(
            "an edit at {start}..{end} falls outside the module"
        ))
    })?;
    output.push_str(&edited);
    if !trailer.is_empty() {
        output.push('\n');
        output.push_str(&trailer);
    }
    Ok(output)
}

/// Text edits against one source, applied together.
#[derive(Default)]
struct Edits {
    /// `(start, end, order, text)`: an insertion has `start == end`.
    edits: Vec<(u32, u32, usize, String)>,
}

impl Edits {
    fn insert(&mut self, at: u32, text: String) {
        let order = self.edits.len();
        self.edits.push((at, at, order, text));
    }

    fn replace(&mut self, span: Span, text: String) {
        let order = self.edits.len();
        self.edits.push((span.start, span.end, order, text));
    }

    /// The edited source, or the span of an edit that does not fit it.
    fn apply(mut self, source: &str) -> std::result::Result<String, (u32, u32)> {
        // Back to front, so earlier offsets stay valid; at one offset the
        // later edit goes first, which leaves the first in front.
        self.edits.sort_by(|a, b| b.0.cmp(&a.0).then(b.2.cmp(&a.2)));
        let mut output = source.to_string();
        for (start, end, _, text) in self.edits {
            let range = start as usize..end as usize;
            if output.get(range.clone()).is_none() {
                return Err((start, end));
            }
            output.replace_range(range, &text);
        }
        Ok(output)
    }
}

/// Point a relative import at the same module from the expanded copy.
fn reroot(edits: &mut Edits, specifier: &StringLiteral<'_>, module_dir: &Path, out_parent: &Path) {
    let value = specifier.value.as_str();
    if !(value.starts_with("./") || value.starts_with("../")) {
        return;
    }
    let target = normalize(&module_dir.join(value));
    let relative = relative_path(out_parent, &target);
    let mut rerooted = slash_path(&relative);
    if !rerooted.starts_with('.') {
        rerooted = format!("./{rerooted}");
    }
    edits.replace(specifier.span, quoted(&rerooted));
}

fn mark_pure_initializers(edits: &mut Edits, declaration: &oxc::ast::ast::VariableDeclaration<'_>) {
    for declarator in &declaration.declarations {
        if let Some(init) = &declarator.init {
            mark_pure(edits, init);
        }
    }
}

/// A top-level call builds config, not state: marking it pure lets a bundler
/// drop it once only the handlers are imported.
fn mark_pure(edits: &mut Edits, expression: &Expression<'_>) {
    if matches!(
        expression,
        Expression::CallExpression(_) | Expression::NewExpression(_)
    ) {
        edits.insert(expression.span().start, "/*#__PURE__*/ ".to_string());
    }
}

/// Every name the module's top level binds: imports and declarations.
fn top_level_names<'a>(program: &'a Program<'a>) -> HashSet<&'a str> {
    let mut names = HashSet::new();
    for statement in &program.body {
        match statement {
            Statement::ImportDeclaration(import) => {
                for specifier in import.specifiers.iter().flatten() {
                    names.insert(specifier.local().name.as_str());
                }
            }
            Statement::VariableDeclaration(declaration) => {
                for declarator in &declaration.declarations {
                    for identifier in declarator.id.get_binding_identifiers() {
                        names.insert(identifier.name.as_str());
                    }
                }
            }
            Statement::FunctionDeclaration(function) => {
                if let Some(id) = &function.id {
                    names.insert(id.name.as_str());
                }
            }
            Statement::ClassDeclaration(class) => {
                if let Some(id) = &class.id {
                    names.insert(id.name.as_str());
                }
            }
            Statement::ExportDeclaration(export) => match &export.declaration {
                Declaration::VariableDeclaration(declaration) => {
                    for declarator in &declaration.declarations {
                        for identifier in declarator.id.get_binding_identifiers() {
                            names.insert(identifier.name.as_str());
                        }
                    }
                }
                Declaration::FunctionDeclaration(function) => {
                    if let Some(id) = &function.id {
                        names.insert(id.name.as_str());
                    }
                }
                Declaration::ClassDeclaration(class) => {
                    if let Some(id) = &class.id {
                        names.insert(id.name.as_str());
                    }
                }
                _ => {}
            },
            _ => {}
        }
    }
    names
}

/// Whether the expression at `target` sits inside a function in `statement`.
fn nested_in_function(statement: &Statement<'_>, target: Span) -> bool {
    struct Finder {
        target: Span,
        depth: u32,
        nested: bool,
    }
    impl<'a> Visit<'a> for Finder {
        fn visit_expression(&mut self, expression: &Expression<'a>) {
            if expression.span() == self.target {
                self.nested = self.depth > 0;
                return;
            }
            walk::walk_expression(self, expression);
        }
        fn visit_function(
            &mut self,
            function: &oxc::ast::ast::Function<'a>,
            flags: oxc::semantic::ScopeFlags,
        ) {
            self.depth += 1;
            walk::walk_function(self, function, flags);
            self.depth -= 1;
        }
        fn visit_arrow_function_expression(
            &mut self,
            arrow: &oxc::ast::ast::ArrowFunctionExpression<'a>,
        ) {
            self.depth += 1;
            walk::walk_arrow_function_expression(self, arrow);
            self.depth -= 1;
        }
    }
    let mut finder = Finder {
        target,
        depth: 0,
        nested: false,
    };
    finder.visit_statement(statement);
    finder.nested
}

/// What would read differently once the module is copied elsewhere.
fn reject_relocation_hazards(program: &Program<'_>) -> std::result::Result<(), String> {
    #[derive(Default)]
    struct Hazards {
        found: Option<String>,
    }
    impl<'a> Visit<'a> for Hazards {
        fn visit_import_expression(&mut self, _: &ImportExpression<'a>) {
            self.found
                .get_or_insert_with(|| "a dynamic `import()`".to_string());
        }
        fn visit_import_meta(&mut self, _: &ImportMeta) {
            self.found
                .get_or_insert_with(|| "`import.meta`".to_string());
        }
    }
    let mut hazards = Hazards::default();
    hazards.visit_program(program);
    match hazards.found {
        Some(hazard) => Err(format!(
            "uses {hazard}, which reads differently once the config is expanded into \
             `.macroforge/config`; import what it needs statically instead"
        )),
        None => Ok(()),
    }
}

/// `path` with `.` and `..` resolved lexically.
fn normalize(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    normalized
}

fn relative_path(from_dir: &Path, to: &Path) -> PathBuf {
    pathdiff::diff_paths(to, from_dir).unwrap_or_else(|| to.to_path_buf())
}

pub(super) fn slash_path(path: &Path) -> String {
    path.components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

pub(super) fn quoted(text: &str) -> String {
    serde_json::Value::String(text.to_string()).to_string()
}

/// The text at `span`, moved to the top level: its later lines lose the
/// indentation of the line it starts on, so they keep their shape relative
/// to the export. Text holding a template literal or a line-continued string
/// is kept as written, since its line breaks may sit inside a string.
fn top_level_text(source: &str, span: Span) -> String {
    let text = slice(source, span);
    if text.contains('`') || text.contains("\\\n") {
        return text.to_string();
    }
    let line_start = source
        .get(..span.start as usize)
        .and_then(|before| before.rfind('\n'))
        .map_or(0, |newline| newline + 1);
    let indent: String = source
        .get(line_start..)
        .unwrap_or("")
        .chars()
        .take_while(|c| *c == ' ' || *c == '\t')
        .collect();
    let mut lines = text.split('\n');
    let mut out = lines.next().unwrap_or("").to_string();
    for line in lines {
        out.push('\n');
        out.push_str(line.strip_prefix(indent.as_str()).unwrap_or(line));
    }
    out
}

fn slice(source: &str, span: Span) -> &str {
    source
        .get(span.start as usize..span.end as usize)
        .unwrap_or("")
}
