/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Generates depth-aware field controller helpers for reactive forms */
export declare function fieldController(...args: Array<unknown>): PropertyDecorator

export declare function FieldController(): ClassDecorator

export declare function JSON(): ClassDecorator

/** Generates depth-aware field controller helpers for reactive forms */
export declare function textAreaController(): PropertyDecorator
