/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface TransformResult {
  code: string
  map?: string
}

/** Transform TypeScript code to JavaScript with macro expansion */
export declare function transformSync(code: string, filepath: string): TransformResult
