import type {
  DecodeContext,
  DecodeOptions,
  EncodeContext,
  FieldError,
  PendingRef,
} from '../endec/index.ts';

/**
 * # Macroforge Traits Module
 *
 * This module defines TypeScript interfaces that correspond to Rust-like traits.
 * These interfaces describe the shape of the methods generated by Macroforge's
 * derive macros for interfaces, enums, and type aliases.
 *
 * For **classes**, the derive macros generate *static* wrapper methods on the
 * class (e.g., `User.clone(user)`) plus standalone functions named after the
 * type (e.g., `userClone(user)`). For **interfaces/enums/type aliases**, only
 * the standalone functions are generated.
 *
 * ## Usage
 *
 * These traits are primarily used for type checking generated code:
 *
 * ```typescript
 * import type { Clone, Debug } from "@macroforge/core/traits";
 *
 * // Type-check that a namespace implements Clone
 * const UserNs: Clone<User> = User;
 * ```
 *
 * @module @macroforge/core/traits
 */

/**
 * Trait for types that can be deep-copied.
 *
 * Analogous to Rust's `Clone` trait. The generated `clone` method creates
 * an independent copy of the value.
 *
 * @template T - The type being cloned
 *
 * @example
 * ```typescript
 * // For classes, use the generated static wrapper:
 * const cloned = User.clone(original);
 *
 * // For any shape (classes, interfaces, enums, type aliases),
 * // use the generated standalone function:
 * const cloned2 = userClone(original);
 * ```
 */
export interface Clone<T> {
  /**
   * Creates a deep copy of the value.
   * @param self - The value to clone
   * @returns A new independent copy of the value
   */
  readonly clone: (self: T) => T;
}

/**
 * Trait for types with a human-readable string representation.
 *
 * Analogous to Rust's `Debug` trait. The generated `toString` method
 * produces a string like `"TypeName { field1: value1, field2: value2 }"`.
 *
 * @template T - The type being formatted
 *
 * @example
 * ```typescript
 * console.log(User.toString(user));
 * // Output: "User { id: 1, name: Alice }"
 * ```
 */
export interface Debug<T> {
  /**
   * Returns a debug string representation of the value.
   * @param self - The value to format
   * @returns A human-readable string for debugging
   */
  readonly toString: (self: T) => string;
}

/**
 * Trait for types with a default value.
 *
 * Analogous to Rust's `Default` trait. The generated `defaultValue` method
 * creates an instance with all fields set to their default values.
 *
 * @template T - The type being constructed
 *
 * @example
 * ```typescript
 * const user = User.defaultValue();
 * // Creates: { id: 0, name: "", active: false }
 * ```
 */
export interface Default<T> {
  /**
   * Creates a new instance with default values for all fields.
   * @returns A new instance with default field values
   */
  readonly defaultValue: () => T;
}

/**
 * Trait for types that support equality comparison.
 *
 * Analogous to Rust's `PartialEq` trait. The generated `equals` method
 * performs structural equality comparison on all non-skipped fields.
 *
 * @template T - The type being compared
 *
 * @example
 * ```typescript
 * if (User.equals(user1, user2)) {
 *   console.log("Users are equal");
 * }
 * ```
 */
export interface PartialEq<T> {
  /**
   * Compares two values for equality.
   * @param self - The first value
   * @param other - The second value (accepts unknown for flexibility)
   * @returns `true` if the values are equal, `false` otherwise
   */
  readonly equals: (self: T, other: unknown) => boolean;
}

/**
 * Trait for types whose equality is total.
 *
 * Analogous to Rust's `Eq` trait: every value equals itself, so `equals`
 * never treats a value as incomparable. Like Rust's, it adds no methods to
 * `PartialEq`, and `@derive(Eq)` requires `@derive(PartialEq)`.
 *
 * @template T - The type being compared
 */
export type Eq<T> = PartialEq<T>;

/**
 * Trait for types that can produce a hash code.
 *
 * Analogous to Rust's `Hash` trait. The generated `hashCode` method
 * computes a 32-bit integer hash suitable for use in hash-based collections.
 *
 * **Hash Contract**: Objects that are equal (via `PartialEq`) must produce
 * the same hash code.
 *
 * @template T - The type being hashed
 *
 * @example
 * ```typescript
 * const hash = User.hashCode(user);
 * // Use in Map: map.set(hash, user);
 * ```
 */
export interface Hash<T> {
  /**
   * Computes a hash code for the value.
   * @param self - The value to hash
   * @returns A 32-bit integer hash code
   */
  readonly hashCode: (self: T) => number;
}

/**
 * Trait for types with partial ordering.
 *
 * Analogous to Rust's `PartialOrd` trait. The generated `partialCompare` method
 * returns a number for comparable values, or `null` for incomparable values.
 * As in Rust, it requires `PartialEq`.
 *
 * @template T - The type being compared
 *
 * @example
 * ```typescript
 * const cmp = User.partialCompare(user1, user2);
 * if (cmp !== null) {
 *   if (cmp < 0) console.log("user1 < user2");
 *   else if (cmp > 0) console.log("user1 > user2");
 *   else console.log("user1 == user2");
 * } else {
 *   console.log("Incomparable");
 * }
 * ```
 */
export interface PartialOrd<T> extends PartialEq<T> {
  /**
   * Compares two values for ordering.
   * @param self - The first value
   * @param other - The second value
   * @returns `-1` if self < other, `0` if equal, `1` if self > other, or `null` if incomparable
   */
  readonly partialCompare: (self: T, other: unknown) => number | null;
}

/**
 * Trait for types with total ordering.
 *
 * Analogous to Rust's `Ord` trait. The generated `compare` method always
 * returns a number, never null: all values are comparable. As in Rust, it
 * requires `Eq` and `PartialOrd`.
 *
 * @template T - The type being compared
 *
 * @example
 * ```typescript
 * // Sort an array using Ord
 * users.sort(User.compare);
 * ```
 */
export interface Ord<T> extends Eq<T>, PartialOrd<T> {
  /**
   * Compares two values for ordering (total order).
   * @param self - The first value
   * @param other - The second value
   * @returns `-1` if self < other, `0` if equal, `1` if self > other
   */
  readonly compare: (self: T, other: T) => number;
}

/**
 * Trait for types that can be encoded to JSON.
 *
 * Analogous to Rust's serde `Serialize` trait. The generated methods
 * convert objects to JSON with cycle detection via `__id`/`__ref` markers.
 *
 * @template T - The type being encoded
 *
 * @example
 * ```typescript
 * const json = User.encode(user);
 * // => '{"name":"Alice"}'
 *
 * const jsonWithMeta = User.encode(user, true);
 * // => '{"__type":"User","__id":0,"name":"Alice"}'
 * ```
 */
export interface Encode<T> {
  /**
   * Encodes the value to a JSON string.
   * @param value - The value to encode
   * @param keepMetadata - If `true`, preserves the `__type` and `__id` cycle
   *   detection markers in the output; by default they are stripped
   * @returns JSON string representation of the value
   */
  readonly encode: (value: T, keepMetadata?: boolean) => string;

  /**
   * Encodes the value to a plain object using an explicit context.
   * Called by nested encoders so that cycle detection state is shared
   * across the whole object graph.
   * @param value - The value to encode
   * @param ctx - A `EncodeContext` from `@macroforge/core/endec`
   * @returns Plain object representation with `__type`/`__id` markers
   */
  readonly encodeWithContext: (
    value: T,
    ctx: EncodeContext,
  ) => Record<string, unknown>;
}

/**
 * Trait for types that can be decoded from JSON.
 *
 * Analogous to Rust's serde `Deserialize` trait. The generated methods
 * parse JSON, resolve `__ref` markers, and validate field values.
 *
 * @template T - The type being decoded
 *
 * @example
 * ```typescript
 * const result = User.decode(data);
 * if (result.success) {
 *   const user = result.value;
 * } else {
 *   console.error(result.errors); // Validation errors
 * }
 * ```
 */
export interface Decode<T> {
  /**
   * Decodes input into a value of type `T`.
   * Automatically detects whether the input is a JSON string or a plain
   * object, and returns a result union instead of throwing.
   * @param input - JSON string or object to decode
   * @param opts - Optional settings (e.g., `{ freeze: true }` to freeze all
   *   decoded objects)
   * @returns `{ success: true, value }` on success, or
   *   `{ success: false, errors }` with field-level validation errors
   */
  readonly decode: (
    input: unknown,
    opts?: DecodeOptions,
  ) =>
    | { success: true; value: T }
    | { success: false; errors: Array<FieldError> };

  /**
   * Decodes a raw object using an explicit context.
   * Called by nested decoders so that reference resolution state is
   * shared across the whole object graph. May return a `PendingRef`
   * placeholder for a forward `__ref` that is resolved later by
   * `ctx.applyPatches()`.
   * @param value - Raw object to decode
   * @param ctx - A `DecodeContext` from `@macroforge/core/endec`
   * @returns The decoded value, or a `PendingRef` marker
   */
  readonly decodeWithContext: (
    value: unknown,
    ctx: DecodeContext,
  ) => T | PendingRef;
}
