//! # Import Registry
//!
//! Unified import registry built during IR lowering, used throughout macro expansion.
//! All insertions are idempotent: duplicates are impossible by design.
//!
//! This module lives in `macroforge_ts_syn` so that [`TsStream`](crate::TsStream) can
//! register imports directly instead of pushing raw patches.

use std::cell::RefCell;
use std::collections::HashMap;

use indexmap::IndexMap;

use crate::abi::ir::type_registry::FileImportEntry;

/// Extract import declarations from a parsed Oxc program.
pub fn collect_file_imports(program: &oxc::ast::ast::Program<'_>) -> Vec<FileImportEntry> {
    use oxc::ast::ast::*;
    let mut imports = Vec::new();

    for stmt in &program.body {
        if let Statement::ImportDeclaration(import) = stmt {
            let module_specifier = import.source.value.to_string();
            let is_type_only = import.import_kind.is_type();

            if let Some(specifiers) = &import.specifiers {
                for specifier in specifiers {
                    match specifier {
                        ImportDeclarationSpecifier::ImportSpecifier(s) => {
                            let local = s.local.name.to_string();
                            let original = if s.imported.name() != s.local.name {
                                Some(s.imported.name().to_string())
                            } else {
                                None
                            };
                            imports.push(FileImportEntry {
                                local_name: local,
                                module_specifier: module_specifier.clone(),
                                original_name: original,
                                is_type_only: is_type_only || s.import_kind.is_type(),
                            });
                        }
                        ImportDeclarationSpecifier::ImportDefaultSpecifier(s) => {
                            imports.push(FileImportEntry {
                                local_name: s.local.name.to_string(),
                                module_specifier: module_specifier.clone(),
                                original_name: Some("default".to_string()),
                                is_type_only,
                            });
                        }
                        ImportDeclarationSpecifier::ImportNamespaceSpecifier(s) => {
                            imports.push(FileImportEntry {
                                local_name: s.local.name.to_string(),
                                module_specifier: module_specifier.clone(),
                                original_name: Some("*".to_string()),
                                is_type_only,
                            });
                        }
                    }
                }
            }
        }
    }

    imports
}

// ============================================================================
// Core types
// ============================================================================

/// A single import from the user's source file.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SourceImport {
    /// The module this identifier is imported from (e.g., `"effect"`, `"./types"`)
    pub source_module: String,
    /// The original exported name, if the import uses an alias.
    /// For `import { Option as EffectOption }`, this is `Some("Option")`.
    pub original_name: Option<String>,
    /// Whether this import is type-only (`import type { ... }` or `import { type ... }`).
    pub is_type_only: bool,
}

/// A source import as a plain record, one per name the file imports.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SourceImportEntry {
    pub local_name: String,
    pub source_module: String,
    pub original_name: Option<String>,
    pub is_type_only: bool,
}

/// An import generated by macro expansion (to be emitted at the top of the file).
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GeneratedImport {
    /// The local name used in the generated code.
    pub local_name: String,
    /// The module to import from.
    pub source_module: String,
    /// The original name if different from local (for `import { X as Y }` patterns).
    pub original_name: Option<String>,
    /// Whether this should be emitted as `import type`.
    pub is_type_only: bool,
}

/// Unified import registry. Built during IR lowering, used throughout expansion.
///
/// All insertions are idempotent: duplicates are impossible by design.
/// The registry has three sections:
/// 1. **Source imports**: pre-populated from the user's AST during lowering. Read-only after creation.
/// 2. **Config imports**: from `macroforge.config.ts` import statements. Name → module.
/// 3. **Generated imports**: accumulated during macro expansion via `request_*` methods.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ImportRegistry {
    /// Source file imports. Key: local_name → entry.
    /// Pre-populated from AST during lowering. Never modified after initial construction.
    source_imports: HashMap<String, SourceImport>,

    /// Generated imports accumulated during macro expansion.
    /// Key: local_name. Insertion order preserved for deterministic output.
    generated: IndexMap<String, GeneratedImport>,

    /// Names an expansion brought into the file from another module's scope,
    /// as a generic alias declared there expands here. Each is also a
    /// generated import, and resolves like a source import.
    #[serde(default)]
    borrowed: HashMap<String, SourceImport>,
}

impl Default for ImportRegistry {
    fn default() -> Self {
        Self::new()
    }
}

impl ImportRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self {
            source_imports: HashMap::new(),
            generated: IndexMap::new(),
            borrowed: HashMap::new(),
        }
    }

    /// Build from Oxc AST.
    pub fn from_program(program: &oxc::ast::ast::Program<'_>, source: &str) -> Self {
        use oxc::ast::ast::*;
        let mut source_imports = HashMap::new();

        source_imports.extend(
            macro_imports_in_comments(&program.comments, source)
                .into_iter()
                .map(|(name, module_src)| {
                    (
                        name,
                        SourceImport {
                            source_module: module_src,
                            original_name: None,
                            is_type_only: false,
                        },
                    )
                }),
        );

        for stmt in &program.body {
            if let Statement::ImportDeclaration(import) = stmt {
                let source_module = import.source.value.to_string();
                if let Some(specifiers) = &import.specifiers {
                    for specifier in specifiers {
                        match specifier {
                            ImportDeclarationSpecifier::ImportSpecifier(s) => {
                                let local_name = s.local.name.to_string();
                                let original_name = if s.imported.name() != s.local.name {
                                    Some(s.imported.name().to_string())
                                } else {
                                    None
                                };
                                source_imports.insert(
                                    local_name,
                                    SourceImport {
                                        source_module: source_module.clone(),
                                        original_name,
                                        is_type_only: import.import_kind.is_type()
                                            || s.import_kind.is_type(),
                                    },
                                );
                            }
                            ImportDeclarationSpecifier::ImportDefaultSpecifier(s) => {
                                source_imports.insert(
                                    s.local.name.to_string(),
                                    SourceImport {
                                        source_module: source_module.clone(),
                                        original_name: Some("default".to_string()),
                                        is_type_only: import.import_kind.is_type(),
                                    },
                                );
                            }
                            ImportDeclarationSpecifier::ImportNamespaceSpecifier(s) => {
                                source_imports.insert(
                                    s.local.name.to_string(),
                                    SourceImport {
                                        source_module: source_module.clone(),
                                        original_name: Some("*".to_string()),
                                        is_type_only: import.import_kind.is_type(),
                                    },
                                );
                            }
                        }
                    }
                }
            }
        }

        Self {
            source_imports,
            generated: IndexMap::new(),
            borrowed: HashMap::new(),
        }
    }

    /// Check if an identifier is available (in source OR already generated).
    pub fn is_available(&self, name: &str) -> bool {
        self.source_imports.contains_key(name) || self.generated.contains_key(name)
    }

    /// Check if a source import is type-only.
    /// Returns false if the import is not found.
    pub fn is_type_only(&self, name: &str) -> bool {
        self.source_imports
            .get(name)
            .map(|si| si.is_type_only)
            .unwrap_or(false)
    }

    /// The module `name` is imported from: by the source file, or by a
    /// [borrowed](Self::borrow_import) import.
    pub fn get_source(&self, name: &str) -> Option<&str> {
        self.source_imports
            .get(name)
            .or_else(|| self.borrowed.get(name))
            .map(|si| si.source_module.as_str())
    }

    /// Resolve alias to original name, for a source or borrowed import.
    /// For `import { Option as EffectOption }`, `resolve_alias("EffectOption")` → `Some("Option")`.
    pub fn resolve_alias(&self, name: &str) -> Option<&str> {
        self.source_imports
            .get(name)
            .or_else(|| self.borrowed.get(name))
            .and_then(|si| si.original_name.as_deref())
    }

    /// Imports `local_name` as a name from another module's scope, which an
    /// expansion uses in this file: a generated import that resolves like
    /// one the source file wrote.
    pub fn borrow_import(
        &mut self,
        local_name: &str,
        original_name: Option<&str>,
        module: &str,
        is_type_only: bool,
    ) {
        self.request_import(local_name, original_name, module, is_type_only);
        self.borrowed.insert(
            local_name.to_string(),
            SourceImport {
                source_module: module.to_string(),
                original_name: original_name.map(str::to_string),
                is_type_only,
            },
        );
    }

    /// Get all source imports as a reference to the internal HashMap.
    pub fn source_map(&self) -> &HashMap<String, SourceImport> {
        &self.source_imports
    }

    /// Get source imports as a flat name→module HashMap (for backward-compat callers).
    pub fn source_modules(&self) -> HashMap<String, String> {
        self.source_imports
            .iter()
            .map(|(name, si)| (name.clone(), si.source_module.clone()))
            .collect()
    }

    /// Get import aliases as a flat local→original HashMap (for backward-compat callers).
    pub fn aliases(&self) -> HashMap<String, String> {
        self.source_imports
            .iter()
            .filter_map(|(name, si)| {
                si.original_name
                    .as_ref()
                    .map(|orig| (name.clone(), orig.clone()))
            })
            .collect()
    }

    /// Export source imports as serializable entries for cross-process transfer.
    pub fn source_import_entries(&self) -> Vec<SourceImportEntry> {
        self.source_imports
            .iter()
            .map(|(name, si)| SourceImportEntry {
                local_name: name.clone(),
                source_module: si.source_module.clone(),
                original_name: si.original_name.clone(),
                is_type_only: si.is_type_only,
            })
            .collect()
    }

    /// Export source imports as the registry's `FileImportEntry` shape so
    /// `TypeRegistry::resolve` and `resolve_generic_aliases` can disambiguate
    /// types whose simple name appears in multiple files.
    pub fn file_import_entries(&self) -> Vec<crate::abi::ir::type_registry::FileImportEntry> {
        use crate::abi::ir::type_registry::FileImportEntry;
        self.source_imports
            .iter()
            .map(|(name, si)| FileImportEntry {
                local_name: name.clone(),
                module_specifier: si.source_module.clone(),
                original_name: si.original_name.clone(),
                is_type_only: si.is_type_only,
            })
            .collect()
    }

    /// Adds source imports, as if the file being expanded declared them.
    /// Lets a test give a context the imports a real file would have.
    pub fn install_source_imports(&mut self, entries: Vec<SourceImportEntry>) {
        for entry in entries {
            self.source_imports.insert(
                entry.local_name,
                SourceImport {
                    source_module: entry.source_module,
                    original_name: entry.original_name,
                    is_type_only: entry.is_type_only,
                },
            );
        }
    }

    /// General-purpose import request. Idempotent: skips if `local_name` already
    /// exists in source or generated imports.
    ///
    /// This is the method TsStream import helpers delegate to.
    pub fn request_import(
        &mut self,
        local_name: &str,
        original_name: Option<&str>,
        module: &str,
        is_type_only: bool,
    ) {
        // Reject dotted names
        if local_name.contains('.') {
            return;
        }

        // Already in source: skip
        if self.source_imports.contains_key(local_name) {
            return;
        }

        // Already generated: a value request upgrades a type-only import, since
        // a value import also serves type positions.
        if let Some(existing) = self.generated.get_mut(local_name) {
            existing.is_type_only &= is_type_only;
            return;
        }

        self.generated.insert(
            local_name.to_string(),
            GeneratedImport {
                local_name: local_name.to_string(),
                source_module: module.to_string(),
                original_name: original_name.map(|s| s.to_string()),
                is_type_only,
            },
        );
    }

    /// Request a namespace import (e.g., `import { DateTime as __mf_DateTime } from "effect"`).
    ///
    /// No-op if `namespace` is already a value import in source.
    /// No-op if `alias` is already in generated.
    pub fn request_namespace_import(&mut self, namespace: &str, module: &str, alias: &str) {
        // If namespace is already available as a non-type-only import, skip
        if let Some(si) = self.source_imports.get(namespace)
            && !si.is_type_only
        {
            return;
        }

        // If alias is already generated, skip
        if self.generated.contains_key(alias) {
            return;
        }

        self.generated.insert(
            alias.to_string(),
            GeneratedImport {
                local_name: alias.to_string(),
                source_module: module.to_string(),
                original_name: Some(namespace.to_string()),
                is_type_only: false,
            },
        );
    }

    /// Request a type-only import (e.g., `import type { Utc } from "effect/DateTime"`).
    ///
    /// No-op if `name` is already in source or generated.
    /// Rejects dotted names (logs warning, returns early).
    pub fn request_type_import(&mut self, name: &str, module: &str) {
        self.request_import(name, None, module, true);
    }

    /// Get an iterator over generated imports.
    pub fn generated_imports(&self) -> impl Iterator<Item = &GeneratedImport> {
        self.generated.values()
    }

    /// Take a snapshot of generated imports and clear them from the registry.
    /// Used by `TsStream::into_result()` to capture imports into `MacroResult`
    /// so they survive encoding across process boundaries.
    pub fn take_generated_imports(&mut self) -> Vec<GeneratedImport> {
        std::mem::take(&mut self.generated).into_values().collect()
    }

    /// Merge a list of generated imports back into the registry.
    /// Used to restore imports from a `MacroResult` (e.g., from an external macro).
    pub fn merge_imports(&mut self, imports: Vec<GeneratedImport>) {
        for import in imports {
            if self.source_imports.contains_key(&import.local_name) {
                continue;
            }
            match self.generated.entry(import.local_name.clone()) {
                indexmap::map::Entry::Occupied(mut entry) => {
                    entry.get_mut().is_type_only &= import.is_type_only;
                }
                indexmap::map::Entry::Vacant(entry) => {
                    entry.insert(import);
                }
            }
        }
    }

    /// Format all generated imports as TypeScript import declarations: one
    /// per module and import kind, in the order each was first requested.
    pub fn emit_generated_imports(&self) -> String {
        let mut declarations: IndexMap<(&str, bool), Vec<String>> = IndexMap::new();
        for import in self.generated.values() {
            let specifier = match &import.original_name {
                Some(original) => format!("{original} as {}", import.local_name),
                None => import.local_name.clone(),
            };
            declarations
                .entry((import.source_module.as_str(), import.is_type_only))
                .or_default()
                .push(specifier);
        }

        let mut lines = String::new();
        for ((module, is_type_only), specifiers) in declarations {
            let keyword = if is_type_only {
                "import type"
            } else {
                "import"
            };
            lines.push_str(&format!(
                "{keyword} {{ {} }} from \"{module}\";\n",
                specifiers.join(", ")
            ));
        }
        lines
    }
}

// ============================================================================
// Thread-local registry: single source of truth for all import state
// ============================================================================

thread_local! {
    /// Single thread-local holding the unified import registry.
    static IMPORT_REGISTRY: RefCell<ImportRegistry> = RefCell::new(ImportRegistry::new());
}

/// Read from the registry (immutable access).
pub fn with_registry<R>(f: impl FnOnce(&ImportRegistry) -> R) -> R {
    IMPORT_REGISTRY.with(|r| f(&r.borrow()))
}

/// Write to the registry (mutable access).
pub fn with_registry_mut<R>(f: impl FnOnce(&mut ImportRegistry) -> R) -> R {
    IMPORT_REGISTRY.with(|r| f(&mut r.borrow_mut()))
}

/// Install a pre-built registry into the thread-local.
pub fn install_registry(registry: ImportRegistry) {
    IMPORT_REGISTRY.with(|r| {
        *r.borrow_mut() = registry;
    });
}

/// Take the registry out of the thread-local, replacing it with an empty one.
pub fn take_registry() -> ImportRegistry {
    IMPORT_REGISTRY.with(|r| std::mem::take(&mut *r.borrow_mut()))
}

/// Clear the registry after expansion.
pub fn clear_registry() {
    IMPORT_REGISTRY.with(|r| {
        *r.borrow_mut() = ImportRegistry::new();
    });
}

// ============================================================================
// JSDoc @import macro comment parsing
// ============================================================================

/// The macro imports declared by a program's `/** import macro { A } from "pkg" */`
/// comments, as macro name to module. Only real comments count: the same text
/// inside a string literal or a doc example is not a directive.
pub fn macro_imports_in_comments(
    comments: &[oxc::ast::Comment],
    source: &str,
) -> HashMap<String, String> {
    let mut out = HashMap::new();
    for comment in comments.iter().filter(|comment| comment.is_block()) {
        let Some(text) = source.get(comment.span.start as usize..comment.span.end as usize) else {
            continue;
        };
        if let Some(body) = text
            .strip_prefix("/**")
            .and_then(|rest| rest.strip_suffix("*/"))
        {
            insert_macro_import_directive(&mut out, body);
        }
    }
    out
}

/// Record the names of the `import macro { A, B } from "pkg"` directive that
/// makes up `body`, a JSDoc comment's text; any other comment adds nothing.
fn insert_macro_import_directive(out: &mut HashMap<String, String>, body: &str) {
    if !crate::jsdoc::is_macro_import_comment(body) {
        return;
    }
    let normalized = normalize_macro_import_body(body);
    let Some(open_brace) = normalized.find('{') else {
        return;
    };
    let Some(close_brace) = normalized[open_brace..]
        .find('}')
        .map(|offset| open_brace + offset)
    else {
        return;
    };
    let Some(from_offset) = normalized[close_brace..].to_ascii_lowercase().find("from") else {
        return;
    };
    let Some(module) =
        extract_quoted_string(&normalized[close_brace + from_offset + "from".len()..])
    else {
        return;
    };
    for name in normalized[open_brace + 1..close_brace].split(',') {
        let name = name.trim();
        if !name.is_empty() {
            out.insert(name.to_string(), module.clone());
        }
    }
}

fn normalize_macro_import_body(body: &str) -> String {
    let mut normalized = String::new();
    for line in body.lines() {
        let mut trimmed = line.trim();
        if let Some(stripped) = trimmed.strip_prefix('*') {
            trimmed = stripped.trim();
        }
        if trimmed.is_empty() {
            continue;
        }
        if !normalized.is_empty() {
            normalized.push(' ');
        }
        normalized.push_str(trimmed);
    }
    normalized
}

fn extract_quoted_string(input: &str) -> Option<String> {
    for (idx, ch) in input.char_indices() {
        if ch == '"' || ch == '\'' {
            let start = idx + 1;
            let rest = &input[start..];
            if let Some(end) = rest.find(ch) {
                return Some(rest[..end].trim().to_string());
            }
            break;
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::macro_imports_in_comments;
    use oxc::allocator::Allocator;
    use oxc::parser::Parser;
    use oxc::span::SourceType;
    use std::collections::HashMap;

    fn macro_imports(source: &str) -> HashMap<String, String> {
        let allocator = Allocator::default();
        let parsed = Parser::new(&allocator, source, SourceType::ts()).parse();
        macro_imports_in_comments(&parsed.program.comments, source)
    }

    #[test]
    fn imports_from_one_module_share_a_declaration() {
        let mut registry = super::ImportRegistry::new();
        registry.request_import("__foreign__aEncode", None, "#macroforge/config", false);
        registry.request_import("__mf_Ctx", Some("Ctx"), "pkg", false);
        registry.request_import("__foreign__aDefault", None, "#macroforge/config", false);
        registry.request_import("__mf_Options", Some("Options"), "pkg", true);
        registry.request_import("__mf_Error", Some("Error"), "pkg", false);
        assert_eq!(
            registry.emit_generated_imports(),
            "import { __foreign__aEncode, __foreign__aDefault } from \"#macroforge/config\";\n\
             import { Ctx as __mf_Ctx, Error as __mf_Error } from \"pkg\";\n\
             import type { Options as __mf_Options } from \"pkg\";\n"
        );
    }

    #[test]
    fn no_generated_imports_emit_nothing() {
        assert_eq!(super::ImportRegistry::new().emit_generated_imports(), "");
    }

    #[test]
    fn a_value_request_upgrades_a_type_only_import() {
        for type_first in [true, false] {
            let mut registry = super::ImportRegistry::new();
            let requests = if type_first {
                [true, false]
            } else {
                [false, true]
            };
            for is_type_only in requests {
                registry.request_import("__mf_Ctx", Some("Ctx"), "pkg", is_type_only);
            }
            assert_eq!(
                registry.emit_generated_imports().trim(),
                "import { Ctx as __mf_Ctx } from \"pkg\";",
                "type-only requested first: {type_first}"
            );
        }
    }

    #[test]
    fn reads_an_import_macro_comment() {
        let imports = macro_imports(
            "/** import macro { Gigaform, $vec } from \"@testground/macro\"; */\nexport {};",
        );
        assert_eq!(
            imports.get("Gigaform").map(String::as_str),
            Some("@testground/macro")
        );
        assert_eq!(
            imports.get("$vec").map(String::as_str),
            Some("@testground/macro")
        );
    }

    #[test]
    fn the_directive_text_inside_a_string_is_not_an_import() {
        let source = "const hint = '`/** import macro {Name} from \"your-package\"; */`';";
        assert!(macro_imports(source).is_empty());
    }

    #[test]
    fn an_example_inside_a_doc_comment_is_not_an_import() {
        let source = "/**\n * Imported via `import macro {Name} from \"package\"`.\n */\nexport function hover() {}";
        assert!(macro_imports(source).is_empty());
    }
}
